### ISSUE TITLE
Recipes imported from Nextcloud have invalid times

### ISSUE THREAD

**Issue by dietrichmd** [hay-kot/mealie#248]
**Describe the bug**
When importing a recipe from Nextcloud, the time of the recipe is shown as PTxHxxM where x=number.  See https://i.imgur.com/h000JCX.png for example

**Steps To Reproduce**
Please be specific!
1. migrations,
2. import recipes from nextcloud'
3. open recipe
4. see invalid time

**Expected behavior**
Time should be displayed in hours and minutes

**Actual Behavior**
Time is shown only in minutes, if that, preceeded by unneeded characters

**Screenshots**
https://i.imgur.com/h000JCX.png

**Device Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Deployment: docker-compose
 - Browser: chrome
 - Version: 89

**Comment by sephrat** [comment]
I also faced this when importing my Nextcloud recipes. I just learned to live with it until I manually edited all my recipes.
This is due to Nextcloud Cookbook overwriting the times with this custom format (technically it should be an ISO 8601 duration format: https://schema.org/Recipe). 

Ideally we could amend the times when importing from Nextcloud Cookbook to overcome this. It's not a complicated logic but it will need some (if not a lot) rework in Mealie.
For now I would recommend manually editing the json files before importing them into Mealie.

**Comment by hay-kot** [comment]
Can you provide a nexcloud file or backup that I can test? I think this might be an easy fix.

**Comment by dietrichmd** [comment]
Sure thing:  http://cloud.dukefamily.net/s/Y9jHccw6RgiCzrF

**Comment by hay-kot** [comment]
Fixed with #248. Will try to get a patch out in the next day or so 🎉

**Comment by hay-kot** [comment]
This has been fixed in [v0.4.1](https://hay-kot.github.io/mealie/changelog/v0.4.1/) 🎉 along with some other NextCloud migration fixed
