### ISSUE TITLE
Request to extend the allowed TLDs for a valid email address

### ISSUE THREAD

**Issue by zaydons** [hay-kot/mealie#261]
Limiting emails addresses to have a max 3-character TLD limits the allowed email addresses to change the default email from.
https://github.com/hay-kot/mealie/blob/b8cddfd6c5fd1a8785a9dff6bc3f10f2cde1b788/frontend/src/mixins/validators.js#L6

As can be seen on the IANA list of valid TLDs, there are quite a few above 3 characters: https://data.iana.org/TLD/tlds-alpha-by-domain.txt

**Comment by hay-kot** [comment]
The validator needs some work. Someone on the discord also brought up that "plus signs in email addresses (subaddressing/plus addressing/dynamic instant aliases) are reported as being incorrect."

I'm open to anyone jumping in on this one, it should be an easy fix, otherwise I'll get to it later this week. Thanks for bringing this up!

**Comment by sephrat** [comment]
Can't we just go with a more laxist validator? It's better to allow a broken address (user's fault) than forbid a valid one. 
I challenge you to develop a regex handling 100% of the cases without any false positive. :-)

On a side note, there are some python packages that do just that, if you really want to stick with a strong validator.
https://pypi.org/project/email-validator/

**Comment by hay-kot** [comment]
This should be fixed in [v0.4.1](https://hay-kot.github.io/mealie/changelog/v0.4.1/) The regex has been slimmed down to limit the scope
