### ISSUE TITLE
Homepage Categories order

### ISSUE THREAD

**Issue by rouggy** [hay-kot/mealie#535]
**Describe the bug**

Cannot change the order of categories in the homepage

**Steps To Reproduce**

Go to Site Settings
Drag and drop categories from All Categories to Homepage Sections
Re-order categories in Home Page Sections
Save

The order I put is not saved accordingly which then do not update the order on the Home Page.

**Expected behavior**

After saving the new order of the Home Page Sections, the order should be saved accordingly

**Actual Behavior**

Order is not saved as it should in Home Page Sections

Thanks

**Comment by sephrat** [comment]
The categories are unordered at the moment. They seem to get sorted alphabetically in the database.
Saving the order requires changes to the database. I believe @hay-kot wanted to get the migration process working for the next release, so we'll have to wait a bit.

**Comment by sephrat** [comment]
A bit off-topic but while working on the frontend settings, I suggest the following ideas:

- [ ] Categories to choose from on the right should only list unused categories (prevents the user from adding twice the same category)
- [ ] Buttons for creation/deletion of categories could be removed from the right panel since the toolbox is better suited for this activity.

**Comment by wengtad** [comment]
It will somehow related to #490 , but not sure how the design is.

**Comment by hay-kot** [comment]
In v1 I'm going to remove the ability to add categories to the homepage and suggest that cookbooks be used instead. As such, I'm going to close this issue.
