### ISSUE TITLE
Can't update recipe image from URL (desktop only)

### ISSUE THREAD

**Issue by verylazyguy** [hay-kot/mealie#548]
**Describe the bug**
Specifying a URL for the image to download doesn't enable the "GET" button. Inspecting the element and modifying the button to not be disabled results in everything working as expected so it's likely just disabled when it shouldn't be

Oddly, it seems to work as expected when on a phone

**Steps To Reproduce**
1. Go to a recipe
2. Click on Edit
3. Click on Image
4. Fill in a URL
5. The "GET" button is still disabled

**Screenshots**
![Screen Shot 2021-06-17 at 2 32 36 PM](https://user-images.githubusercontent.com/4371276/122454340-49bc4600-cf79-11eb-8c55-be70819335cc.png)

**Device Information (please complete the following information):**
 - OS: Mac
 - Deployment: docker-compose
 - Browser: Firefox
 - Version: 0.5.1

**Comment by wengtad** [comment]
@hay-kot there is conflict between the fix for #459. For the upload file button able to use for new recipe during creation (of course for edit too), but for URL Get button, only for after recipe created, which mean the recipe must exists first, correct? 

So before create (need your advise on the text):
![image](https://user-images.githubusercontent.com/12437747/122500574-a37a4a00-d025-11eb-9f70-e5b49a967685.png)

After create:
![image](https://user-images.githubusercontent.com/12437747/122500605-b260fc80-d025-11eb-8dee-920fede5c5fd.png)

will this better?

**Comment by hay-kot** [comment]
@wengtad Nailed it! Looks good to me
