### ISSUE TITLE
Lost connection to API while logged in after sleep/wake

### ISSUE THREAD

**Issue by DOFfactory** [hay-kot/mealie#599]
**Describe the bug**
The access to the API is lost after putting a computer on sleep and waking up. This happens even if the user is still logged in. The only way how to fix it currently is to logout and login again.

**Steps To Reproduce**
Please be specific!
1. Go to mealie and log in
2. Put computer on sleep for a while
3. Wake it up
4. Try to import a URL with a recipe
5. See the error

**Sample Log**
```
INFO:     172.27.0.1:0 - "GET /api/recipes/summary HTTP/1.1" 200 OK
INFO:     172.27.0.1:0 - "GET /api/debug/version HTTP/1.1" 200 OK
INFO:     172.27.0.1:0 - "GET /api/auth/refresh HTTP/1.1" 401 Unauthorized
```

**Expected behavior**
The API should not lose connection while the user is logged in.

**Comment by hay-kot** [comment]
This is expected behavior. If you are inactive your token expires and you can no longer access the site. You can set the token time through an ENV variables. [See the documentation](https://hay-kot.github.io/mealie/documentation/getting-started/install/#env-variables)

In the future there will be support for a "Stay Logged In" function. See #493
