### ISSUE TITLE
"Dinner This Week" displays first meal plan in planner rather than the meal plan for the current week

### ISSUE THREAD

**Issue by shiruken** [hay-kot/mealie#648]
**Describe the bug**
The *Dinner This Week* page will always display the first meal plan in the planner rather than the meal plan for the current week.

**Steps To Reproduce**
1. Define multiple meal plans covering more than the current week
   - Meal Plan 1: July 18 - 24
   - Meal Plan 2: July 25 - July 31
   - Meal Plan 3: August 1 - August 7
2. Click on *Dinner This Week*
3. The first meal plan (Meal Plan 1) will always be displayed rather than the meal plan for the current week.

**Expected behavior**
*Dinner This Week* should return the meal plan that covers the current week. This is how the *Dinner Today* page works.

**Actual Behavior**
*Dinner This Week* returns the meal plan that was entered first.

**Device Information (please complete the following information):**
 - OS: Unraid 6.9.2
 - Deployment: Docker
 - Browser: Chrome 
 - Version: 0.5.3

**Additional context**
It is unclear what the best practice is for managing Meal Plans. Should old ones just be deleted by the user? That would allow the *Dinner This Week* page to function properly. However, it is useful to be able to reference past meal plans.

**Comment by hay-kot** [comment]
I'm not really sure what the best approach here is either. I'm inclined to suggest that deleting meal-plans is probably the easiest way. I suppose we could prune them 1-2 days after their end date? That would be an easy-ish add.

An alternative may be... Determine week range and then return first match within the week - Potentially computationally heavy...probably insignificant. Problems would be, when does a week start, would have to setup custom handling based of env variable or something? If it's last night of the 'week', would I get next weeks meal-plan or this weeks?

**Comment by shiruken** [comment]
Another potential alternative would be to display the most recently created Meal Plan under the assumption that that's the one the user currently wants to see. Might also be useful to sort the Meal Plans under the Meal Planner in reverse so the newest one is listed first.

**Comment by sephrat** [comment]
In my opinion this bug report shows a design flaw (no offence!), at least from the point of view of my workflow. Having to create a meal plan before planning a single meal is cumbersome, and the fact that you can create concurrent meal plans is error prone. I feel like it just gets in your way of planning your meals.
My suggestion may be drastic, but why not simply drop the notion of meal plans altogether, and consider meals like a single event on a calendar view? Vuetify has views for calendars (https://vuetifyjs.com/en/components/calendars/#click). The meal planner could use the month view, and the "dinner this week" the weekly view, even though I'm not sure how we could nicely integrate side meals. It would make archiving unnecessary: you can still browse through past months but your past plans are not in your face anymore.
Also, this may be a step towards having multiple meals per day (in my culture/country it makes sense to plan meals both for lunch and for dinner), even though it's not really related to this topic, and even less to this issue 😄 

Sorry for being off-topic, but since I know the frontend is getting revamped and there is no easy solution for this issue, I thought now would be the time to suggest this.

**Comment by hay-kot** [comment]
Welp. As with most things I say I'm not going to do I'm going to this. it's become evident that doing what @sephrat suggests would just be way easier than trying to implement the current data structure. I actually got it mostly working w/ drag-and-drop in a few hours. Below is a rough, working example of where I'm headed. 

![mealplan-drag-and-drop](https://user-images.githubusercontent.com/64056131/132925033-346a6efb-9345-4417-a3bc-7d1084db637f.gif)

**Comment by rzaccari** [comment]
I love this approach.  We do 2 weeks planning at a time so short of calculating week ranges, none of the other thoughts would work.  I like to keep previous plans around just so I can figure out what we did last X.

**Comment by hay-kot** [comment]
New meal planner Is in the finale stages and is up on the beta site. Any feed back on the new planner would be greatly appreciated. 

https://beta.mealie.io/meal-plan/planner

**Comment by kabukimandelux** [comment]
> 
> 
> New meal planner Is in the finale stages and is up on the beta site. Any feed back on the new planner would be greatly appreciated.
> 
> https://beta.mealie.io/meal-plan/planner

Looks really great, quite often I do change ideas last minute and change a recipe from one day to another. It's quite a "hassle" without the drag and drop, so this looks perfect to me.

**Comment by wasper17** [comment]
Love the beta site, looks like it fixes most of the issues I noticed.
